### ISSUE TITLE
Add more variables to use different test nodes

### ISSUE THREAD

**Issue by nklomp** [PaulBernier/factomjs#14]
Hi Paul,

As you may know I am setting up a CI server for multiple Factom clients, multiple versions (dev/release) and both networks (test/main). I want to be able to configure against which hosts, ports and protocols/schemes the tests are run.

I see in the factomjs client there is some support for environment variables to steer these, but some are missing.

Most importantly the protocol connect option is missing, as well as the walletd env options.
See https://github.com/PaulBernier/factomjs/blob/master/test/factom-cli.integration.spec.js#L21

It would be great if you could add support for factom/walletd tests to take env-variables for ports, hosts and protocols.

**Comment by PaulBernier** [comment]
Hi Niels,

That makes sense. I have added pretty much all connection parameters as env variables (they all have default values so they are not required to be provided): https://github.com/PaulBernier/factomjs/blob/master/test/factom-cli.integration.spec.js#L20

Note that there isn't really any test against walletd, the only one there is de-activated because I have never set up a permanent reachable walletd instance.

**Comment by nklomp** [comment]
Cool thx. That will help a lot. Will test probably tomorrow

**Comment by PaulBernier** [comment]
Resolving this issue, feel free to re-open a new one if you need more variables.
